### ISSUE TITLE
Section layout 2 seems broken

### ISSUE THREAD

**Issue by sakshityagi** [BuildFire/eCommercePlugin#4]
![screenshot-localhost 63342 2015-11-05 23-04-33](https://cloud.githubusercontent.com/assets/3328800/10976423/c95103b0-8411-11e5-8e41-9ac3940dac0e.png)

**Comment by sakshityagi** [comment]
@jdm135

**Comment by jdm135** [comment]
@sakshityagi This should be taken care of when my SDK merge is pulled. Please test tonight and let me know if there are any issues.

**Comment by sakshityagi** [comment]
@jdm135 Still seems broken. Also I have added class according to info-bar styling which you told us. Please confirm if its correct.

![screenshot-localhost 63342 2015-11-19 10-32-56](https://cloud.githubusercontent.com/assets/3328800/11262757/2bab064a-8ea9-11e5-87fe-3eef02f1029d.png)

**Comment by sakshityagi** [comment]
Working now.
