### ISSUE TITLE
Item list layout does not have tabs in the bottom like wireframes to change layouts: grid or list

### ISSUE THREAD

**Issue by sakshityagi** [BuildFire/eCommercePlugin#6]
![ecommerce item list layout 1](https://cloud.githubusercontent.com/assets/3328800/11180595/f193b7d2-8c81-11e5-8b5c-3992aae05fa9.png)

**Comment by sakshityagi** [comment]
@jdm135

**Comment by jdm135** [comment]
@sakshityagi Created pull request, once it's merged, you will see my changes. I couldn't test, so please test and let me know if there are any issues.

**Comment by sakshityagi** [comment]
Working.
